//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFirstProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SECURITY_DB
    {
        public int ID { get; set; }
        public string FULL_NAME { get; set; }
        public string ROLES { get; set; }
        public string SECURE_PWD { get; set; }
    }
}
